version: "3.7"

services:
  tgbot:
    container_name: bot
    build:
      context: .
    command: python tg_bot_ChatGPT.py
    restart: always
    env_file:
      - ".env"
    volumes:
      - ./MyHelp_bot:/MyHelp_bot/

