version: "3.1"

services:
  tgbot:
    image: deimandar/myhelp_bot
    container_name: bot
    build:
      context: .
    command: python3 MyHelp_bot/tg_bot_ChatGPT.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"


networks:
  botnet:
    driver: bridge